### ISSUE TITLE
Typo on Kuzzle core class on Documentation

### ISSUE THREAD

**Issue by Yoann-Abbes** [kuzzleio/sdk-jvm#28]
https://docs.kuzzle.io/sdk/jvm/1/core-classes/kuzzle/constructor/ -> Kuzzle typo not the same as others

**Comment by Shiranuit** [comment]
In this file [kuzzle/index.md](https://github.com/kuzzleio/sdk-jvm/blob/master/doc/1/core-classes/kuzzle/index.md) change de `code` property to `true`
