### ISSUE TITLE
SDK should ensure that the body is a HashMap

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/sdk-jvm#62]
## Description

The `body` of a request can only be a `HashMap` so the SDK should ensure that the `query` argument of the `Query()` method contains a valid `body`

**Comment by Shiranuit** [comment]
That's not the case, in fact it is only required to give the `Query` method an `HashMap<String, Object>`

In this case the `body` property can be any object that we can serialize, ie: Number, String, Boolean, Array, HashMap
```
Map<String, Object> query = new HashMap<>();
query.put("controller", "logistic-object/item");
query.put("action", "create");
query.put("_id", "myItem4");
query.put("body", body)
```

I suspect there is another bug when users are putting a String in the body, I will take a look at it
