### ISSUE TITLE
Exceptions are wrapped in ExecutionException

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/sdk-jvm#63]
## Description

Exceptions should not be wrapped in `java.util.concurrent.ExecutionException`.

For example, when creating a document who already exists, the exception should be `io.kuzzle.sdk.coreClasses.exceptions.ApiErrorException`

**Comment by Shiranuit** [comment]
We do not control this behaviour, this is how the Java Runtime handles exceptions with futures that do throw, the Runtime wraps the exception with ExecutionException, it cannot be changed unfortunately.
